name: Nightly Azure Smoke Test

on:
  schedule:
    - cron: "0 2 * * *"  # 2:00 AM UTC nightly
  workflow_dispatch:

jobs:
  smoke-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0  # full history so we can rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt pandas matplotlib

      - name: Run smoke tests (test-only mode) and save outputs
        run: |
          chmod +x deploy_and_test.sh
          ./deploy_and_test.sh --test-only | tee smoketest_output.txt
          python3 <<'PYCODE'
          # ... smoke test Python code ...
          PYCODE

      - name: Generate latency trend chart
        run: |
          python3 <<'PYCODE'
          # ... chart generation Python code ...
          PYCODE

      - name: Update README last updated timestamp
        run: |
          ts="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          sed -i "s|<!--LAST_UPDATED-->.*<!--LAST_UPDATED-->|<!--LAST_UPDATED-->${ts}<!--LAST_UPDATED-->|" README.md

      - name: Calculate latest average latency and uptime, create badge JSONs
        run: |
          python3 <<'PYCODE'
          # ... badge JSON generation Python code ...
          PYCODE

      - name: Commit and push all changes once (with rebase safety net)
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add monitoring/smoketest_results.csv monitoring/latency_trends.png README.md badges/latency.json badges/uptime.json
          git fetch origin main
          if ! git pull --rebase origin main; then
            echo "❌ Merge conflict or rebase error detected. Aborting push."
            git rebase --abort || true
            exit 1
          fi
          git commit -m "Nightly smoke test updates: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push origin main

      - name: Push latency.json to Gist
        if: success()
        run: |
          if [ ! -s badges/latency.json ]; then
            echo "❌ ERROR: badges/latency.json is missing or empty."
            exit 1
          fi
          curl -s -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/gists/93c19d78e2f7ea5477c83cfa3bb5b2d3 \
            -d @- <<EOF
          {
            "files": {
              "latency.json": {
                "content": "$(cat badges/latency.json)"
              }
            }
          }
          EOF

      - name: Push uptime.json to Gist
        if: success()
        run: |
          if [ ! -s badges/uptime.json ]; then
            echo "❌ ERROR: badges/uptime.json is missing or empty."
            exit 1
          fi
          curl -s -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/gists/8902bf762ca4daa4a38e4e7b4b0c483f \
            -d @- <<EOF
          {
            "files": {
              "uptime.json": {
                "content": "$(cat badges/uptime.json)"
              }
            }
          }
          EOF